name: Mirror to Gitee
on:
  push:
  workflow_dispatch:

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Mirror push to Gitee
        run: |
          git remote add gitee https://oauth2:${{ secrets.GITEE_TOKEN }}@gitee.com/sam-dancing/${{ github.event.repository.name }}.git
          git push gitee --mirror
